export const stateAndCities: { [key: string]: string[] } = {
    "Johor": [
        "Johor Bahru",
        "Iskandar Puteri",
        "Pasir Gudang",
        "Kulai",
        "Batu Pahat",
        "Muar",
        "Kluang",
        "Segamat",
        "Pontian",
        "Kota Tinggi",
        "Mersing",
        "Tangkak",
        "Simpang Renggam",
        "Yong Peng",
        "Parit Raja",
        "Senai",
        "Ulu Tiram",
        "Skudai",
        "Pekan Nanas",
        "Gelang Patah"
    ],
    "Kedah": [
        "Alor Setar",
        "Sungai Petani",
        "Kulim",
        "Jitra",
        "Yan",
        "Kuah",
        "Pendang",
        "Gurun",
        "Baling",
        "Pokok Sena",
        "Bandar Baharu",
        "Kupang",
        "Lunas",
        "Sik",
        "Kuala Nerang",
        "Padang Serai",
        "Bedong",
        "Langkawi"
    ],
    "Kelantan": [
        "Kota Bharu",
        "Pasir Mas",
        "Tumpat",
        "Tanah Merah",
        "Kuala Krai",
        "Pasir Puteh",
        "Bachok",
        "Gua Musang",
        "Machang",
        "Pangkal Kalong",
        "Wakaf Bharu",
        "Rantau Panjang",
        "Jeli",
        "Kuala Balah",
        "Dabong"
    ],
    "Melaka": [
        "Melaka City",
        "Alor Gajah",
        "Jasin",
        "Masjid Tanah",
        "Merlimau",
        "Batu Berendam",
        "Ayer Keroh",
        "Bemban",
        "Sungai Udang",
        "Bukit Katil",
        "Klebang",
        "Pulau Sebang",
        "Kuala Sungai Baru",
        "Batang Melaka"
    ],
    "Negeri Sembilan": [
        "Seremban",
        "Port Dickson",
        "Nilai",
        "Bahau",
        "Tampin",
        "Kuala Pilah",
        "Rembau",
        "Gemas",
        "Pedas",
        "Simpang Durian",
        "Rantau",
        "Mantin",
        "Si Rusa",
        "Linggi",
        "Senawang"
    ],
    "Pahang": [
        "Kuantan",
        "Temerloh",
        "Bentong",
        "Mentakab",
        "Raub",
        "Jerantut",
        "Pekan",
        "Kuala Lipis",
        "Cameron Highlands",
        "Rompin",
        "Maran",
        "Muadzam Shah",
        "Bukit Tinggi",
        "Gambang",
        "Genting Highlands",
        "Kuala Rompin",
        "Bandar Tun Razak"
    ],
    "Perak": [
        "Ipoh",
        "Taiping",
        "Sitiawan",
        "Teluk Intan",
        "Batu Gajah",
        "Kampar",
        "Lumut",
        "Sungai Siput",
        "Kuala Kangsar",
        "Tanjung Malim",
        "Tapah",
        "Bidor",
        "Parit Buntar",
        "Slim River",
        "Gopeng",
        "Menglembu",
        "Pangkor",
        "Tronoh"
    ],
    "Perlis": [
        "Kangar",
        "Arau",
        "Kuala Perlis",
        "Padang Besar",
        "Beseri",
        "Sanglang",
        "Simpang Empat",
        "Utan Aji",
        "Jejawi",
        "Pauh"
    ],
    "Pulau Pinang": [
        "George Town",
        "Butterworth",
        "Bukit Mertajam",
        "Nibong Tebal",
        "Kepala Batas",
        "Air Itam",
        "Bayan Lepas",
        "Perai",
        "Tanjung Tokong",
        "Balik Pulau",
        "Teluk Bahang",
        "Batu Ferringhi",
        "Teluk Kumbar",
        "Simpang Ampat",
        "Permatang Pauh"
    ],
    "Sabah": [
        "Kota Kinabalu",
        "Sandakan",
        "Tawau",
        "Lahad Datu",
        "Keningau",
        "Semporna",
        "Kudat",
        "Ranau",
        "Beaufort",
        "Kota Belud",
        "Papar",
        "Tuaran",
        "Tenom",
        "Kunak",
        "Beluran",
        "Putatan",
        "Penampang",
        "Tambunan"
    ],
    "Sarawak": [
        "Kuching",
        "Miri",
        "Sibu",
        "Bintulu",
        "Limbang",
        "Sarikei",
        "Sri Aman",
        "Kapit",
        "Serian",
        "Marudi",
        "Batu Kawa",
        "Mukah",
        "Lawas",
        "Simanggang",
        "Dalat",
        "Asajaya",
        "Saratok",
        "Lundu"
    ],
    "Selangor": [
        "Shah Alam",
        "Petaling Jaya",
        "Subang Jaya",
        "Klang",
        "Ampang",
        "Kajang",
        "Sepang",
        "Rawang",
        "Hulu Langat",
        "Gombak",
        "Semenyih",
        "Cyberjaya",
        "Kuala Selangor",
        "Banting",
        "Bangi",
        "Batu Caves",
        "Port Klang",
        "Puchong",
        "Selayang",
        "Sungai Buloh"
    ],
    "Terengganu": [
        "Kuala Terengganu",
        "Kemaman",
        "Dungun",
        "Chukai",
        "Marang",
        "Jerteh",
        "Kerteh",
        "Kuala Berang",
        "Paka",
        "Besut",
        "Setiu",
        "Kuala Besut",
        "Rantau Abang",
        "Merchang",
        "Kemasik"
    ],
    "Wilayah Persekutuan Kuala Lumpur": [
        "Kuala Lumpur City Centre",
        "Wangsa Maju",
        "Setapak",
        "Bangsar",
        "Bukit Bintang",
        "Cheras",
        "Kepong",
        "Sri Petaling",
        "Setiawangsa",
        "Mont Kiara",
        "Damansara",
        "Sentul",
        "Brickfields",
        "Taman Tun Dr Ismail",
        "Segambut"
    ],
    "Wilayah Persekutuan Labuan": [
        "Labuan Town",
        "Rancha-Rancha",
        "Nagalang",
        "Pohon Batu",
        "Batu Manikar",
        "Layang-Layangan",
        "Tanjung Aru",
        "Kiansam",
        "Sungai Bedaun",
        "Sungai Keling"
    ],
    "Wilayah Persekutuan Putrajaya": [
        "Precinct 1",
        "Precinct 2",
        "Precinct 3",
        "Precinct 4",
        "Precinct 5",
        "Precinct 6",
        "Precinct 7",
        "Precinct 8",
        "Precinct 9",
        "Precinct 10",
        "Precinct 11",
        "Precinct 12",
        "Precinct 13",
        "Precinct 14",
        "Precinct 15",
        "Precinct 16",
        "Precinct 17",
        "Precinct 18",
        "Precinct 19",
        "Precinct 20"
    ]
};

export default stateAndCities;